
package com.ganesh.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FundTranferManager", targetNamespace = "http://ws.ganesh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FundTranferManager {


    /**
     * 
     * @param initiateFundTransferRequest
     * @return
     *     returns com.ganesh.ws.InitiateFundTransferReply
     */
    @WebMethod
    @WebResult(name = "InitiateFundTransferReply", targetNamespace = "")
    @RequestWrapper(localName = "initiateFundTransfer", targetNamespace = "http://ws.ganesh.com/", className = "com.ganesh.ws.InitiateFundTransfer")
    @ResponseWrapper(localName = "initiateFundTransferResponse", targetNamespace = "http://ws.ganesh.com/", className = "com.ganesh.ws.InitiateFundTransferResponse")
    public InitiateFundTransferReply initiateFundTransfer(
        @WebParam(name = "initiateFundTransferRequest", targetNamespace = "")
        InitiateFundTransferRequest initiateFundTransferRequest);

}
